name = "BinaryTrees"
uuid = "45b67b40-3a40-4200-8e87-5782b82a11fe"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
